eat-it:
  auth:
    url: https://eat-it-auth-app.herokuapp.com
  users:
    url: https://eat-it-users-app.herokuapp.com

spring:
  data:
    mongodb:
      database: productsDB
      uri: ${MONGO_URL}

server:
  port: ${PORT:8080}