eat-it:
  auth:
    url: http://localhost:8082
  users:
    url: http://localhost:8080

spring:
  data:
    mongodb:
      database: productsDB
      uri: mongodb://localhost:27017

server:
  port: 8081